version: "3.8"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: k8Fqs&N5Io
      POSTGRES_DB: parking
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parking"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - base-network
    ports:
      - 5432:5432
volumes:
  postgres-data:
networks:
  base-network:
    driver: bridge